### ISSUE TITLE
This issue is coming which extracting video

### ISSUE THREAD

**Issue by parthh2** [HaarigerHarald/android-youtubeExtractor#109]
error comes

W/System.err: java.io.FileNotFoundException: https://s.ytimg.com/yts/jsbin/null
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.decipherSignature(YouTubeExtractor.java:461)
W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:401)
W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:199)
W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:35)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:764)

Please tell me ASAP

**Comment by mrhussnain** [comment]
i have solution contact me at mrhussnain3@gmail.com

**Comment by deshan** [comment]
Getting the same error? Any solution? It was worked previously.
