### ISSUE TITLE
SparseArray<YtFile> sparseArray return null  while using this url https://www.youtube.com/watch?v=JJhSOTc6ZjU  can anyone help me

### ISSUE THREAD

**Issue by dixit12345** [HaarigerHarald/android-youtubeExtractor#125]
java.io.FileNotFoundException: https://s.ytimg.com/yts/jsbin/null
2019-12-27 12:50:59.995 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
2019-12-27 12:50:59.995 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
2019-12-27 12:50:59.995 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
2019-12-27 12:50:59.995 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.decipherSignature(YouTubeExtractor.java:454)
2019-12-27 12:50:59.996 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:394)
2019-12-27 12:50:59.996 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:194)
2019-12-27 12:50:59.996 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:33)
2019-12-27 12:50:59.996 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2019-12-27 12:50:59.997 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-12-27 12:50:59.997 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2019-12-27 12:50:59.997 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-12-27 12:50:59.997 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-12-27 12:50:59.998 32204-32229/com.androidwave.youtubeexoplayer W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-12-27 12:51:01.295 32204-32204/com.androidwave.youtubeexoplayer D/ViewRootImpl@5ed2fb9[MainActivity]: stopped(false) old=true

**Comment by askinucuncu** [comment]
I have the same problem. Please help me.

**Comment by naveedhassan913** [comment]
I have made a library that can extract yt urls perfectly and fast just check it
[https://github.com/naveedhassan913/YouTubeExtractor]()

**Comment by dixit12345** [comment]
Hello Naveed,

Is this a library also available for Ios and I am facing the same problem
in ios.
https://github.com/naveedhassan913/YouTubeExtractor

Thanks,
Amit Dixit

**Comment by naveedhassan913** [comment]
Sorry its not available ios

**Comment by dixit12345** [comment]
Hello Naveed,


I have one question which is related to youtube extractor,  in the future
may be a chance your library stop provide extractor URL or youtube can
block extractor URLs?. some time it gives URL and sometimes not.

https://github.com/naveedhassan913/YouTubeExtractor



Thanks & Regards,

Amit Dixit

**Comment by naveedhassan913** [comment]
@dixit12345 No its working perfectly right now....As far as future.... I'll update if any issue in lib....

**Comment by gobankii20** [comment]
change URL youtube in library 
from "https://youtube.googleapis.com/v/" to "https://youtube.googleapis.com/v3/" in file YouTubeExtractor.java

**Comment by JabirDev** [comment]
Try update to v2.0.0 ! It working for me.

**Comment by hhyeok1026** [comment]
@gobankii20   I tried this, but it is not working properly.

@JabirDev  I tried this, but it is not working properly too..

I am testing with Galaxy s10, s6 edge,
The Galaxy S10 works better.
The s6edge rarely works after multiple attempts.
