### ISSUE TITLE
Not Extract URL

### ISSUE THREAD

**Issue by musickitapp** [HaarigerHarald/android-youtubeExtractor#142]
`W/System.err: java.io.FileNotFoundException: https://s.ytimg.com/yts/jsbin/null
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at at.huber.youtubeExtractor.YouTubeExtractor.decipherSignature(YouTubeExtractor.java:436)
        at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:394)
        at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:196)
        at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:34)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by RadamireZ** [comment]
I receive the same error

**Comment by aliia** [comment]
I'm getting this error for enciphered videos

**Comment by RadamireZ** [comment]
So using http, it's enough to figure out the problem? or the lab need to be upgated?

**Comment by bunaif** [comment]
working without any problems.

any URL for example?

**Comment by RadamireZ** [comment]
For example this ID not work for me : Ej0ME8xdiF8

**Comment by bunaif** [comment]
fixed, close this issue.

**Comment by RadamireZ** [comment]
in my case the problem persist, try this: 9dmpUjW18MQ

**Comment by RadamireZ** [comment]
I tried again the first video and it doesn't work for me, but for some videos works.
url in http and double true as parameters

**Comment by bunaif** [comment]
@RadamireZ  
> in my case the problem persist, try this: 9dmpUjW18MQ

![Screenshot_٢٠٢٠٠٤١٩-٠٣١٨٢٩_YouTube Download](https://user-images.githubusercontent.com/20098154/79673694-020f2280-81ed-11ea-8730-78a7b5a75cf1.jpg)


try to clear the cache.

**Comment by RadamireZ** [comment]
i'm using it from source code, maybe it doesn't take the last update?

**Comment by bunaif** [comment]
make sure you are using the latest provided apk from here 
https://github.com/HaarigerHarald/android-youtubeExtractor/releases/tag/v2.1.0

after install, clear app data and try again.

**Comment by RadamireZ** [comment]
after sync the gradle, it still not work. I can only extract some video, maybe it's only my problem.

**Comment by andj207** [comment]
v2.1.0 works for me. Big thanks!

**Comment by bunaif** [comment]
> after sync the gradle, it still not work. I can only extract some video, maybe it's only my problem. 

Go to build > clean project after cleaning Rebuild project.

**Comment by RadamireZ** [comment]
Still null on extraction complete in my code.

**Comment by bunaif** [comment]
I think you downloaded the library folder and added it to Android Studio without making any changes.
You are not used 
`implementation 'com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT'` ?

**Comment by RadamireZ** [comment]
Yes, i' m using that line to import it , i'm not using any static libs yet.
