### ISSUE TITLE
Does not extract File not found exception

### ISSUE THREAD

**Issue by habibmhamadi** [HaarigerHarald/android-youtubeExtractor#143]
does not extract url, i am getting file not found exception.

this is my code :

`String id = "WN4Xec0bNmo";`
`new YouTubeExtractor(this){`
        `@Override`
        `protected void onExtractionComplete(SparseArray<YtFile> ytFiles, VideoMeta videoMeta) {`
       `if (ytFiles != null) {`
       ` int itag = 22;`
       `String downloadUrl = ytFiles.get(itag).getUrl();`
   `}`
 `}`
`}.extract(id,true,true);`

this is the error i get:
2020-04-26 10:37:33.660 16983-17498/com.habib.youtubedownloader W/System.err: java.io.FileNotFoundException: https://www.youtube.com/get_video_info?video_id=WN4Xec0bNmo&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FWN4Xec0bNmo
2020-04-26 10:37:33.661 16983-17498/com.habib.youtubedownloader W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
2020-04-26 10:37:33.661 16983-17498/com.habib.youtubedownloader W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
2020-04-26 10:37:33.661 16983-17498/com.habib.youtubedownloader W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
2020-04-26 10:37:33.661 16983-17498/com.habib.youtubedownloader W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:219)
2020-04-26 10:37:33.662 16983-17498/com.habib.youtubedownloader W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:195)
2020-04-26 10:37:33.662 16983-17498/com.habib.youtubedownloader W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:34)
2020-04-26 10:37:33.663 16983-17498/com.habib.youtubedownloader W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2020-04-26 10:37:33.663 16983-17498/com.habib.youtubedownloader W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-26 10:37:33.663 16983-17498/com.habib.youtubedownloader W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2020-04-26 10:37:33.663 16983-17498/com.habib.youtubedownloader W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-04-26 10:37:33.663 16983-17498/com.habib.youtubedownloader W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-04-26 10:37:33.664 16983-17498/com.habib.youtubedownloader W/System.err:     at java.lang.Thread.run(Thread.java:764)

i get the same error with all tags.

**Comment by ParryPatel021** [comment]
@habibmhamadi Have you got some workaround for this?

**Comment by bunaif** [comment]
@ParryPatel021 check this [147#issuecomment-638439366](https://github.com/HaarigerHarald/android-youtubeExtractor/issues/147#issuecomment-638439366)

**Comment by ParryPatel021** [comment]
Thank you @xibr 
I have resolved it by update the library version.
