### ISSUE TITLE
java.io.EOFException in samsung s3

### ISSUE THREAD

**Issue by sunilsunny565** [HaarigerHarald/android-youtubeExtractor#16]
This is the complete log.

```
 java.io.EOFException
     at java.util.zip.GZIPInputStream.readFully(GZIPInputStream.java:206)
     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:98)
     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:81)
     at libcore.net.http.HttpEngine.initContentStream(HttpEngine.java:547)
     at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:850)
     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
     at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:177)
     at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
     at at.huber.youtubeExtractor.YouTubeUriExtractor.getStreamUrls(YouTubeUriExtractor.java:208)
     at at.huber.youtubeExtractor.YouTubeUriExtractor.doInBackground(YouTubeUriExtractor.java:158)
     at at.huber.youtubeExtractor.YouTubeUriExtractor.doInBackground(YouTubeUriExtractor.java:32)
     at android.os.AsyncTask$2.call(AsyncTask.java:287)
     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
     at java.lang.Thread.run(Thread.java:841)
```

Didn't have this issue on other devices though.Will check on more devices.

**Comment by sunilsunny565** [comment]
My bad .Wrong video id was extracted.
