### ISSUE TITLE
System.err: java.io.FileNotFoundException: https://www.youtube.com/get_video_info

### ISSUE THREAD

**Issue by TechComet** [HaarigerHarald/android-youtubeExtractor#174]
Hi,

I have this problem
```
W/System.err: java.io.FileNotFoundException: https://www.youtube.com/get_video_info?video_id=cGxi8YVfbLA&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FcGxi8YVfbLA
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at net.techcomet.myapplication.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:220)
        at net.techcomet.myapplication.YouTubeExtractor.doInBackground(YouTubeExtractor.java:196)
        at net.techcomet.myapplication.YouTubeExtractor.doInBackground(YouTubeExtractor.java:34)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by cryinrain69** [comment]
i had the same problem.
API get_video_info not found.
Looks like Youtube has changed the get link mechanism.

**Comment by BHASKAR911** [comment]
I had the same problem. It was working 3 or 4 days ago but not working today.

**Comment by rajnesh-culturealley** [comment]
same issue

**Comment by Niraj0009** [comment]
Same issue ....
   java.io.FileNotFoundException: https://www.youtube.com/get_video_info?video_id=mciibqxFOk8&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FmciibqxFOk8

getStreamUrls(YouTubeExtractor.java:220)

**Comment by hijacker4163** [comment]
Same issue.

java.io.FileNotFoundException: https://www.youtube.com/get_video_info?video_id=HnvOSb-gP-s&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FHnvOSb-gP-s
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:220)
at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:196)
at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:34)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

**Comment by gajananinfotech20** [comment]
any solution??

**Comment by TechComet** [comment]
I use sampleapp it's work!
Strange thing..

**Comment by saurabhgoyal795** [comment]
any solution ??

**Comment by gajananinfotech20** [comment]
BasicNetwork.performRequest: Unexpected response code 403 for http://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=8VwCrbXxi60

E/erorr::: com.android.volley.AuthFailureError

**Comment by MahmoudMabrok** [comment]
same error seems youtube changed their mechanism

**Comment by saurabhgoyal795** [comment]
what is solution of this ?

**Comment by DatUET** [comment]
add html5=1. Sample:
https://www.youtube.com/get_video_info?video_id=mciibqxFOk8&html5=1&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FmciibqxFOk8

**Comment by sahaypratik** [comment]
@DatUET It worked. Thanks

**Comment by MahmoudMabrok** [comment]
@DatUET 
could upload a version to JitPack ?

**Comment by MahmoudMabrok** [comment]
or
please what file to change 
@DatUET

**Comment by MahmoudMabrok** [comment]
i uploaded it here 
 implementation 'com.github.MahmoudMabrok:android-youtubeExtractor:master-SNAPSHOT'

**Comment by Niraj0009** [comment]
> https://www.youtube.com/get_video_info?video_id=mciibqxFOk8&html5=1&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FmciibqxFOk8

how to use...pls help

**Comment by MahmoudMabrok** [comment]
@Niraj0009 
you can use this fork and it will work with you, 

implementation 'com.github.MahmoudMabrok:android-youtubeExtractor:master-SNAPSHOT'

**Comment by yadvendrayadav123** [comment]
@MahmoudMabrok 
com.github.MahmoudMabrok:android-youtubeExtractor:master-SNAPSHOT its written in Kotlin, how to use this library in java project

**Comment by yadvendrayadav123** [comment]
same issue

**Comment by MahmoudMabrok** [comment]
@yadvendrayadav123 
sorry for this, it is also use coroutine which not supported with java,

**Comment by Tan108** [comment]
I tried https://www.youtube.com/get_video_info?html5=1&video_id=e-s6FyfSb3Y&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2Fe-s6FyfSb3Y&c=TVHTML5&cver=6.20180913  still not working for me.

**Comment by vaderot** [comment]
Same for me 

java.io.FileNotFoundException: https://www.youtube.com/get_video_info?html5=1&video_id=FdoiaitKTBs&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FFdoiaitKTBs&c=TVHTML5&cver=6.20180913

It worked yesterday. Stoped working today morning

**Comment by hariprakashnagar** [comment]
Same issue, i am facing

**Comment by ghost** [comment]
Any solution ??

**Comment by MohitDer** [comment]
> i uploaded it here implementation 'com.github.MahmoudMabrok:android-youtubeExtractor:master-SNAPSHOT'

How To Use this

**Comment by MahmoudMabrok** [comment]
> > i uploaded it here implementation 'com.github.MahmoudMabrok:android-youtubeExtractor:master-SNAPSHOT'
> 
> How To Use this

it should be same like current lib, I created that fork so not need to wait for PR to be merged. 


I did not try my fork recently, but it was working.
