### ISSUE TITLE
YouTubeExtractor.onExtractionComplete() returns ytFiles as null for certain youtube link

### ISSUE THREAD

**Issue by cmeng-git** [HaarigerHarald/android-youtubeExtractor#187]
YouTubeExtractor.onExtractionComplete() returns ytFiles as null for certain youtube link

e.g.: https://youtu.be/vCKCkc8llaM

2021-06-19 06:46:31.129 14932-17879/org.cog.hymnchtv W/System.err: java.io.FileNotFoundException: https://www.youtube.com/get_video_info?html5=1&video_id=vCKCkc8llaM&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FvCKCkc8llaM
2021-06-19 06:46:31.129 14932-17879/org.cog.hymnchtv W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
2021-06-19 06:46:31.130 14932-17879/org.cog.hymnchtv W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
2021-06-19 06:46:31.130 14932-14932/org.cog.hymnchtv D/ScrollView: initGoToTop
2021-06-19 06:46:31.131 14932-17879/org.cog.hymnchtv W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
2021-06-19 06:46:31.131 14932-17879/org.cog.hymnchtv W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:220)
2021-06-19 06:46:31.132 14932-17879/org.cog.hymnchtv W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:196)
2021-06-19 06:46:31.132 14932-17879/org.cog.hymnchtv W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:34)
2021-06-19 06:46:31.133 14932-17879/org.cog.hymnchtv W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
2021-06-19 06:46:31.133 14932-17879/org.cog.hymnchtv W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-06-19 06:46:31.134 14932-17879/org.cog.hymnchtv W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
2021-06-19 06:46:31.134 14932-17879/org.cog.hymnchtv W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-06-19 06:46:31.135 14932-17879/org.cog.hymnchtv W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-06-19 06:46:31.135 14932-17879/org.cog.hymnchtv W/System.err:     at java.lang.Thread.run(Thread.java:923)

**Comment by karthikstrk** [comment]
@cmeng-git  did you fixed it!?

**Comment by cmeng-git** [comment]
No. The link is part of the android playlst. Look like android is constantly changing its internal info access. I see it is not an easy task for the developer to upkeep with youtube continuous changes.

To avoid future error in android url extraction, I have moved to use the following for playing the youtube url.
https://github.com/PierfrancescoSoffritti/android-youtube-player
